[world]
name = "blob_arena-0.10.0"
seed = "blob-arena-0.10.0"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
account_address = "0x049848982e9b089A1F4eb5e1cd12aB58bE55Feb6937bc9CfcAD34c2Dfd0a6df8"

[namespace]
default = "betsy"
mappings = { "example" = ["betsy_example_actions", "BetsyExampleGame"] }

[writers]
betsy = ["betsy-bet"]
example = ["example-betsy_example_actions"]


[init_call_args]
betsy-bet = [
    "0x049848982e9b089A1F4eb5e1cd12aB58bE55Feb6937bc9CfcAD34c2Dfd0a6df8",
    "0x19",
]
