[world]
name = "betsy"
seed = "blob-arena-0.11.11"

[namespace]
default = "betsy"
mappings = { "example" = ["betsy_example_actions", "BetsyExampleGame"] }

[env]
rpc_url = "https://api.cartridge.gg/rpc/starknet-sepolia"
account_address = "0x058e3B49d870f08C96a02f794C82b5f6C868c074DeaDD6bA04E8d2194723B5bd"
keystore_path = "/home/ben/sn-accounts/0x058e3b49d870f08c96a02f794c82b5f6c868c074deadd6ba04e8d2194723b5bd-keystore.json"

[writers]
betsy = ["betsy-bet"]
example = ["example-betsy_example_actions"]


[init_call_args]
betsy-bet = [
    "0x058e3B49d870f08C96a02f794C82b5f6C868c074DeaDD6bA04E8d2194723B5bd",
    "0x19",
]
